version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    environment:
      - DB_HOST=localhost
      - DB_DATABASE=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
